{
	"version": 1581428563,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/playerbody-sheet0.png",
		"images/playerbody-sheet1.png",
		"images/playerhand-sheet0.png",
		"images/item-sheet0.png",
		"images/item-sheet1.png",
		"images/item-sheet2.png",
		"images/npc-sheet0.png",
		"images/npc-sheet1.png",
		"images/npc-sheet2.png",
		"images/colormapfg-sheet0.png",
		"images/colormapbg-sheet0.png",
		"images/dummycamera-sheet0.png",
		"images/playerfootr-sheet0.png",
		"images/creditsbackground-sheet0.png",
		"images/title1-sheet0.png",
		"images/title1-sheet1.png",
		"images/title1-sheet2.png",
		"images/decor-sheet0.png",
		"images/decor-sheet1.png",
		"images/colorwheel-sheet0.png",
		"images/credits1-sheet0.png",
		"images/calangames1-sheet0.png",
		"images/talbone_mask-sheet0.png",
		"images/and1-sheet0.png",
		"images/lights-sheet0.png",
		"images/ggj__fonte-sheet0.png",
		"images/ggj__fonte-sheet1.png",
		"images/ggj__fonte-sheet2.png",
		"images/audioplayers-sheet0.png",
		"media/item given.ogg",
		"media/item pickup.ogg",
		"media/quest success.ogg",
		"media/risada 1.ogg",
		"media/risada 2.ogg",
		"media/risada 3.ogg",
		"media/risada 4.ogg",
		"media/risada 5.ogg",
		"media/ui hover.ogg",
		"media/ui select.ogg",
		"media/walk.ogg",
		"media/s_drums.ogg",
		"media/s_knife.ogg",
		"media/s_flower.ogg",
		"media/s_panties.ogg",
		"media/s_brush.ogg",
		"media/s_glasses.ogg",
		"media/s_cat.ogg",
		"media/s_guitar.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}