{
	"version": 1580808171,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/playerbody-sheet0.png",
		"images/playerbody-sheet1.png",
		"images/playerhand-sheet0.png",
		"images/item-sheet0.png",
		"images/item-sheet1.png",
		"images/item-sheet2.png",
		"images/npc-sheet0.png",
		"images/npc-sheet1.png",
		"images/npc-sheet2.png",
		"images/colormapfg-sheet0.png",
		"images/colormapbg-sheet0.png",
		"images/dummycamera-sheet0.png",
		"images/playerfootr-sheet0.png",
		"images/creditsbackground-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite2-sheet1.png",
		"images/sprite2-sheet2.png",
		"images/decor-sheet0.png",
		"images/decor-sheet1.png",
		"images/colorwheel-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/talbone_mask-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"media/item given.m4a",
		"media/item given.ogg",
		"media/item pickup.m4a",
		"media/item pickup.ogg",
		"media/quest success.m4a",
		"media/quest success.ogg",
		"media/risada 1.m4a",
		"media/risada 1.ogg",
		"media/risada 2.m4a",
		"media/risada 2.ogg",
		"media/risada 3.m4a",
		"media/risada 3.ogg",
		"media/risada 4.m4a",
		"media/risada 4.ogg",
		"media/risada 5.m4a",
		"media/risada 5.ogg",
		"media/ui hover.m4a",
		"media/ui hover.ogg",
		"media/ui select.m4a",
		"media/ui select.ogg",
		"media/walk.m4a",
		"media/walk.ogg",
		"media/bard.m4a",
		"media/drums.m4a",
		"media/killer.m4a",
		"media/lovers.m4a",
		"media/naked.m4a",
		"media/painter.m4a",
		"media/student.m4a",
		"media/witch.m4a",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}